- name: PLAY
  hosts: local
  connection: local
  tasks:
  - name: hello from play 1nand task1
    ansible.builtin.debug:
      msg: "Hello from PLAY1 AND TASK-1"
  
  - name: hello from play2 and task2
    ansible.builtin.debug:
      msg: "Hello from PLAAY2 AND TASK-2"

- name: play2
  hosts: local
  connection: local
  tasks:
  - name: hello from play2 and task2
    ansible.builtin.debug:
      msg: "hello from PLAY2 ans Tsk1"
