- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible # equal to course= ANsible in shell , shell we refer $VAR or ${VAR}
    DURATION: 10HR
    TRAINER: Eswar
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"

  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"

  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"