- name: undrstandvars preferennce\
  hosts: local
  connection: local
  vars:
    GREETING: "hello from PLAY"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: GREETING
    prompt: Please eter the GREETING
    private: false
  tasks:
  - name: print the GREETING
    vars:
      GREETING "Hello from TASK"
    ansible.builtin.debug:
      msg: "{{GREETING}}"